version: "2"
sql:
  - schema: "../../../../schema.sql"
    queries: "./query"
    engine: "sqlite"
    gen:
      go:
        out: "./sql"
        package: "sql"
        emit_json_tags: true
        emit_interface: false
