// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dashboard.sql

package sql

import (
	"context"
	"database/sql"
)

const getExerciseVolumeSummary = `-- name: GetExerciseVolumeSummary :many
SELECT
    ev.exercise_id,
    ev.exercise_name,
    SUM(ev.volume) AS total_volume,
    COUNT(*) AS total_sets,
    SUM(ev.reps) AS total_reps,
    MAX(ev.weight) AS max_weight
FROM
    vw_exercise_volumes ev
WHERE
    ev.device_id = ?1           -- $1: device_id
    AND ev.performed_at >= ?2   -- $2: start_date (inclusive)
    AND ev.performed_at < ?3    -- $3: end_date (exclusive)
GROUP BY
    ev.exercise_id, ev.exercise_name
ORDER BY
    total_volume DESC, ev.exercise_name ASC
`

type GetExerciseVolumeSummaryParams struct {
	DeviceID      string `json:"device_id"`
	PerformedAt   string `json:"performed_at"`
	PerformedAt_2 string `json:"performed_at_2"`
}

type GetExerciseVolumeSummaryRow struct {
	ExerciseID   string          `json:"exercise_id"`
	ExerciseName string          `json:"exercise_name"`
	TotalVolume  sql.NullFloat64 `json:"total_volume"`
	TotalSets    int64           `json:"total_sets"`
	TotalReps    sql.NullFloat64 `json:"total_reps"`
	MaxWeight    interface{}     `json:"max_weight"`
}

// Get total volume per exercise for a given device within a date range.
func (q *Queries) GetExerciseVolumeSummary(ctx context.Context, arg GetExerciseVolumeSummaryParams) ([]GetExerciseVolumeSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, getExerciseVolumeSummary, arg.DeviceID, arg.PerformedAt, arg.PerformedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExerciseVolumeSummaryRow
	for rows.Next() {
		var i GetExerciseVolumeSummaryRow
		if err := rows.Scan(
			&i.ExerciseID,
			&i.ExerciseName,
			&i.TotalVolume,
			&i.TotalSets,
			&i.TotalReps,
			&i.MaxWeight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMuscleVolumeSummary = `-- name: GetMuscleVolumeSummary :many
SELECT
    muscle_id,
    muscle_name,
    SUM(volume) AS total_volume
FROM
    vw_muscle_volumes -- Use View 3
WHERE
    device_id = ? -- $1: device_id
    AND performed_at >= ? -- $2: start_date (inclusive)
    AND performed_at < ?  -- $3: end_date (exclusive)
GROUP BY
    muscle_id, muscle_name
ORDER BY
    total_volume DESC, muscle_name ASC
`

type GetMuscleVolumeSummaryParams struct {
	DeviceID      string `json:"device_id"`
	PerformedAt   string `json:"performed_at"`
	PerformedAt_2 string `json:"performed_at_2"`
}

type GetMuscleVolumeSummaryRow struct {
	MuscleID    string          `json:"muscle_id"`
	MuscleName  string          `json:"muscle_name"`
	TotalVolume sql.NullFloat64 `json:"total_volume"`
}

// Get total volume per muscle group for a given device within a date range.
func (q *Queries) GetMuscleVolumeSummary(ctx context.Context, arg GetMuscleVolumeSummaryParams) ([]GetMuscleVolumeSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, getMuscleVolumeSummary, arg.DeviceID, arg.PerformedAt, arg.PerformedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMuscleVolumeSummaryRow
	for rows.Next() {
		var i GetMuscleVolumeSummaryRow
		if err := rows.Scan(&i.MuscleID, &i.MuscleName, &i.TotalVolume); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalVolumeAveragePerWeek = `-- name: GetTotalVolumeAveragePerWeek :one
WITH WeeklyVolumes AS (
    SELECT
        strftime('%Y-%W', performed_at) AS year_week,
        SUM(volume) AS weekly_total_volume
    FROM
        vw_workout_set_details
    WHERE
        device_id = ? -- $1: device_id
        AND performed_at >= ? -- $2: start_date (inclusive)
        AND performed_at < ?  -- $3: end_date (exclusive)
    GROUP BY
        year_week
)
SELECT
    AVG(weekly_total_volume) AS average_weekly_volume
FROM
    WeeklyVolumes
`

type GetTotalVolumeAveragePerWeekParams struct {
	DeviceID      string `json:"device_id"`
	PerformedAt   string `json:"performed_at"`
	PerformedAt_2 string `json:"performed_at_2"`
}

// Calculate the overall average weekly volume for a device over a specified period.
// This first calculates weekly sums, then averages those sums.
func (q *Queries) GetTotalVolumeAveragePerWeek(ctx context.Context, arg GetTotalVolumeAveragePerWeekParams) (sql.NullFloat64, error) {
	row := q.db.QueryRowContext(ctx, getTotalVolumeAveragePerWeek, arg.DeviceID, arg.PerformedAt, arg.PerformedAt_2)
	var average_weekly_volume sql.NullFloat64
	err := row.Scan(&average_weekly_volume)
	return average_weekly_volume, err
}

const getWeeklyVolumeSummary = `-- name: GetWeeklyVolumeSummary :many
SELECT
    strftime('%Y-%W', performed_at) AS year_week, -- Format: YYYY-WW (e.g., '2024-01')
    SUM(volume) AS total_volume
FROM
    vw_workout_set_details -- Use View 1
WHERE
    device_id = ? -- $1: device_id
    AND performed_at >= ? -- $2: start_date (inclusive, e.g., 'YYYY-MM-DD')
    AND performed_at < ?  -- $3: end_date (exclusive, e.g., 'YYYY-MM-DD')
GROUP BY
    year_week
ORDER BY
    year_week ASC
`

type GetWeeklyVolumeSummaryParams struct {
	DeviceID      string `json:"device_id"`
	PerformedAt   string `json:"performed_at"`
	PerformedAt_2 string `json:"performed_at_2"`
}

type GetWeeklyVolumeSummaryRow struct {
	YearWeek    interface{}     `json:"year_week"`
	TotalVolume sql.NullFloat64 `json:"total_volume"`
}

// Get total volume per week for a given device within a date range.
// Weeks start on Monday ('%Y-%W'). Use '%Y-%w' for Sunday start (0=Sunday).
func (q *Queries) GetWeeklyVolumeSummary(ctx context.Context, arg GetWeeklyVolumeSummaryParams) ([]GetWeeklyVolumeSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, getWeeklyVolumeSummary, arg.DeviceID, arg.PerformedAt, arg.PerformedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWeeklyVolumeSummaryRow
	for rows.Next() {
		var i GetWeeklyVolumeSummaryRow
		if err := rows.Scan(&i.YearWeek, &i.TotalVolume); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
