// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: device.sql

package sql

import (
	"context"
	"database/sql"
)

const getDevice = `-- name: GetDevice :one
SELECT id, user_id, created_at, last_seen_at
FROM devices
WHERE id = ?
`

func (q *Queries) GetDevice(ctx context.Context, id string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const upsertDevice = `-- name: UpsertDevice :exec
INSERT INTO devices (id, user_id, created_at, last_seen_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  user_id = excluded.user_id,
  last_seen_at = excluded.last_seen_at
`

type UpsertDeviceParams struct {
	ID         string         `json:"id"`
	UserID     sql.NullString `json:"user_id"`
	CreatedAt  string         `json:"created_at"`
	LastSeenAt string         `json:"last_seen_at"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error {
	_, err := q.db.ExecContext(ctx, upsertDevice,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.LastSeenAt,
	)
	return err
}
