// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: menu.sql

package sql

import (
	"context"
)

const listMenusByDeviceId = `-- name: ListMenusByDeviceId :many
SELECT
    id,
    device_id,
    name,
    description,
    sort_order,
    created_at,
    updated_at
FROM
    menus
WHERE
    device_id = ?
ORDER BY
    sort_order ASC,
    created_at DESC
`

func (q *Queries) ListMenusByDeviceId(ctx context.Context, deviceID string) ([]Menu, error) {
	rows, err := q.db.QueryContext(ctx, listMenusByDeviceId, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Menu
	for rows.Next() {
		var i Menu
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
