// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: menu.sql

package sql

import (
	"context"
	"database/sql"
)

const listMenusByUserId = `-- name: ListMenusByUserId :many
SELECT
    id,
    name,
    description,
    sort_order,
    created_at,
    updated_at
FROM
    menus
WHERE
    user_id = ?
ORDER BY
    sort_order ASC,
    created_at DESC
`

type ListMenusByUserIdRow struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	SortOrder   int64          `json:"sort_order"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

func (q *Queries) ListMenusByUserId(ctx context.Context, userID string) ([]ListMenusByUserIdRow, error) {
	rows, err := q.db.QueryContext(ctx, listMenusByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMenusByUserIdRow
	for rows.Next() {
		var i ListMenusByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
