// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: menu.sql

package sql

import (
	"context"
	"database/sql"
)

const createMenu = `-- name: CreateMenu :one
INSERT INTO menus (
    id,
    device_id,
    name,
    description,
    sort_order,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, device_id, name, description, sort_order, created_at, updated_at
`

type CreateMenuParams struct {
	ID          string         `json:"id"`
	DeviceID    string         `json:"device_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	SortOrder   int64          `json:"sort_order"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

func (q *Queries) CreateMenu(ctx context.Context, arg CreateMenuParams) (Menu, error) {
	row := q.db.QueryRowContext(ctx, createMenu,
		arg.ID,
		arg.DeviceID,
		arg.Name,
		arg.Description,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMenu = `-- name: GetMenu :one
SELECT id, device_id, name, description, sort_order, created_at, updated_at
FROM menus
WHERE id = ?
`

func (q *Queries) GetMenu(ctx context.Context, id string) (Menu, error) {
	row := q.db.QueryRowContext(ctx, getMenu, id)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMenusByDeviceId = `-- name: ListMenusByDeviceId :many
SELECT
    id,
    device_id,
    name,
    description,
    sort_order,
    created_at,
    updated_at
FROM
    menus
WHERE
    device_id = ?
ORDER BY
    sort_order ASC,
    created_at DESC
`

func (q *Queries) ListMenusByDeviceId(ctx context.Context, deviceID string) ([]Menu, error) {
	rows, err := q.db.QueryContext(ctx, listMenusByDeviceId, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Menu
	for rows.Next() {
		var i Menu
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
