// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sql

import (
	"database/sql"
)

type Exercise struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	UserID    interface{} `json:"user_id"`
	CreatedAt string      `json:"created_at"`
	UpdatedAt string      `json:"updated_at"`
}

type ExerciseMuscle struct {
	ExerciseID string `json:"exercise_id"`
	MuscleID   string `json:"muscle_id"`
}

type Menu struct {
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	SortOrder   int64          `json:"sort_order"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

type MenuExercise struct {
	MenuID     string `json:"menu_id"`
	ExerciseID string `json:"exercise_id"`
	Position   int64  `json:"position"`
}

type Muscle struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Workout struct {
	ID          string      `json:"id"`
	UserID      string      `json:"user_id"`
	MenuID      string      `json:"menu_id"`
	PerformedAt string      `json:"performed_at"`
	Rpe         interface{} `json:"rpe"`
	Rir         interface{} `json:"rir"`
	CreatedAt   string      `json:"created_at"`
	UpdatedAt   string      `json:"updated_at"`
}

type WorkoutSet struct {
	ID         string          `json:"id"`
	WorkoutID  string          `json:"workout_id"`
	ExerciseID string          `json:"exercise_id"`
	Weight     float64         `json:"weight"`
	Reps       int64           `json:"reps"`
	Volume     sql.NullFloat64 `json:"volume"`
}
