// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sql

import (
	"database/sql"
)

type Device struct {
	ID         string         `json:"id"`
	UserID     sql.NullString `json:"user_id"`
	CreatedAt  string         `json:"created_at"`
	LastSeenAt string         `json:"last_seen_at"`
}

type Exercise struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	DeviceID  interface{} `json:"device_id"`
	CreatedAt string      `json:"created_at"`
	UpdatedAt string      `json:"updated_at"`
}

type ExerciseMuscle struct {
	ExerciseID string `json:"exercise_id"`
	MuscleID   string `json:"muscle_id"`
}

type Menu struct {
	ID          string         `json:"id"`
	DeviceID    string         `json:"device_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	SortOrder   int64          `json:"sort_order"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

type MenuExercise struct {
	MenuID     string `json:"menu_id"`
	ExerciseID string `json:"exercise_id"`
	Position   int64  `json:"position"`
}

type Muscle struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type VwExerciseVolume struct {
	SetID        string          `json:"set_id"`
	WorkoutID    string          `json:"workout_id"`
	PerformedAt  string          `json:"performed_at"`
	DeviceID     string          `json:"device_id"`
	SetOrder     int64           `json:"set_order"`
	Volume       sql.NullFloat64 `json:"volume"`
	ExerciseID   string          `json:"exercise_id"`
	ExerciseName string          `json:"exercise_name"`
}

type VwMuscleVolume struct {
	SetID        string          `json:"set_id"`
	WorkoutID    string          `json:"workout_id"`
	PerformedAt  string          `json:"performed_at"`
	DeviceID     string          `json:"device_id"`
	SetOrder     int64           `json:"set_order"`
	Volume       sql.NullFloat64 `json:"volume"`
	ExerciseID   string          `json:"exercise_id"`
	ExerciseName string          `json:"exercise_name"`
	MuscleID     string          `json:"muscle_id"`
	MuscleName   string          `json:"muscle_name"`
}

type VwWorkoutSetDetail struct {
	SetID        string          `json:"set_id"`
	WorkoutID    string          `json:"workout_id"`
	SetOrder     int64           `json:"set_order"`
	Weight       float64         `json:"weight"`
	Reps         int64           `json:"reps"`
	Volume       sql.NullFloat64 `json:"volume"`
	Interval     sql.NullInt64   `json:"interval"`
	SetCreatedAt string          `json:"set_created_at"`
	SetUpdatedAt string          `json:"set_updated_at"`
	PerformedAt  string          `json:"performed_at"`
	DeviceID     string          `json:"device_id"`
}

type Workout struct {
	ID          string `json:"id"`
	DeviceID    string `json:"device_id"`
	MenuID      string `json:"menu_id"`
	PerformedAt string `json:"performed_at"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type WorkoutSet struct {
	ID        string          `json:"id"`
	WorkoutID string          `json:"workout_id"`
	SetOrder  int64           `json:"set_order"`
	Weight    float64         `json:"weight"`
	Reps      int64           `json:"reps"`
	Volume    sql.NullFloat64 `json:"volume"`
	Interval  sql.NullInt64   `json:"interval"`
	CreatedAt string          `json:"created_at"`
	UpdatedAt string          `json:"updated_at"`
}
