// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: workout.sql

package sql

import (
	"context"
	"database/sql"
)

const createWorkout = `-- name: CreateWorkout :exec
INSERT INTO workouts (id, device_id, menu_id, performed_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateWorkoutParams struct {
	ID          string `json:"id"`
	DeviceID    string `json:"device_id"`
	MenuID      string `json:"menu_id"`
	PerformedAt string `json:"performed_at"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) CreateWorkout(ctx context.Context, arg CreateWorkoutParams) error {
	_, err := q.db.ExecContext(ctx, createWorkout,
		arg.ID,
		arg.DeviceID,
		arg.MenuID,
		arg.PerformedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createWorkoutSet = `-- name: CreateWorkoutSet :exec
INSERT INTO workout_sets (id, workout_id, exercise_id, weight, reps, rpe, rir)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateWorkoutSetParams struct {
	ID         string          `json:"id"`
	WorkoutID  string          `json:"workout_id"`
	ExerciseID string          `json:"exercise_id"`
	Weight     float64         `json:"weight"`
	Reps       int64           `json:"reps"`
	Rpe        sql.NullFloat64 `json:"rpe"`
	Rir        sql.NullInt64   `json:"rir"`
}

func (q *Queries) CreateWorkoutSet(ctx context.Context, arg CreateWorkoutSetParams) error {
	_, err := q.db.ExecContext(ctx, createWorkoutSet,
		arg.ID,
		arg.WorkoutID,
		arg.ExerciseID,
		arg.Weight,
		arg.Reps,
		arg.Rpe,
		arg.Rir,
	)
	return err
}
