// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sql

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

// エクササイズ種目
type Exercise struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	// NULLの場合は公式提供の種目
	UserID    sql.NullString `json:"user_id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

// エクササイズとターゲット部位の関連付け
type ExerciseMuscle struct {
	ExerciseID uuid.UUID `json:"exercise_id"`
	MuscleID   uuid.UUID `json:"muscle_id"`
}

// トレーニングメニュー
type Menu struct {
	ID uuid.UUID `json:"id"`
	// ClerkのユーザーID
	UserID      string         `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	// メニューの表示順
	SortOrder int32     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// メニューとエクササイズの関連付け
type MenuExercise struct {
	MenuID     uuid.UUID `json:"menu_id"`
	ExerciseID uuid.UUID `json:"exercise_id"`
	// メニュー内でのエクササイズの順序
	Position int32 `json:"position"`
}

// 部位
type Muscle struct {
	ID uuid.UUID `json:"id"`
	// 部位名
	Name string `json:"name"`
}

// 特定の日のワークアウト記録
type Workout struct {
	ID uuid.UUID `json:"id"`
	// ClerkのユーザーID
	UserID string `json:"user_id"`
	// 実行したメニューのID
	MenuID uuid.UUID `json:"menu_id"`
	// ワークアウト実行日時
	PerformedAt time.Time `json:"performed_at"`
	// 主観的運動強度 (1-10)
	Rpe sql.NullString `json:"rpe"`
	// レップス・イン・リザーブ (0-5)
	Rir       sql.NullInt16 `json:"rir"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

// ワークアウト内の具体的なセット記録
type WorkoutSet struct {
	ID uuid.UUID `json:"id"`
	// 所属するワークアウトID
	WorkoutID uuid.UUID `json:"workout_id"`
	// 実行したエクササイズ種目ID
	ExerciseID uuid.UUID `json:"exercise_id"`
	// 使用重量 (kg)
	Weight string `json:"weight"`
	// レップ数
	Reps int32 `json:"reps"`
	// ボリューム (重量 * レップ数)
	Volume sql.NullString `json:"volume"`
}
