// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: workouts.sql

package sql

import (
	"context"

	"github.com/google/uuid"
)

const getWorkoutByID = `-- name: GetWorkoutByID :one
SELECT id, user_id, menu_id, performed_at, rpe, rir, created_at, updated_at FROM workouts WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWorkoutByID(ctx context.Context, id uuid.UUID) (Workout, error) {
	row := q.db.QueryRowContext(ctx, getWorkoutByID, id)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MenuID,
		&i.PerformedAt,
		&i.Rpe,
		&i.Rir,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkoutsByUserID = `-- name: ListWorkoutsByUserID :many
SELECT id, user_id, menu_id, performed_at, rpe, rir, created_at, updated_at FROM workouts WHERE user_id = $1 ORDER BY performed_at DESC
`

func (q *Queries) ListWorkoutsByUserID(ctx context.Context, userID string) ([]Workout, error) {
	rows, err := q.db.QueryContext(ctx, listWorkoutsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MenuID,
			&i.PerformedAt,
			&i.Rpe,
			&i.Rir,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
